/** Shared mock data for employer flow E2E specs. */

export const EMPLOYER_PROFILE = {
  clientId: 1,
  clientName: 'TechCorp',
  industry: 'IT Services',
  email: 'hr@techcorp.com',
  contactNo: '9988776655',
  website: 'https://techcorp.com',
  city: 'Mumbai',
  address: '123 Tech Park',
  logoUrl: null,
  description: 'Leading IT services company',
};

export const APPLICANT_ROW = {
  jobSubscriberMapId: 1,
  subscriberId: 100,
  fullName: 'Ravi Kumar',
  designation: 'Software Engineer',
  city: 'Bengaluru',
  experience: '3 years',
  jobStatus: 'Active',
  status: 'New' as const,
  skills: ['React', 'Node.js'],
  company: 'TechCorp',
  notice: '30 days',
  appliedOn: '2026-08-15T10:00:00.000Z',
};

export const APPLICANT_DETAIL = {
  ...APPLICANT_ROW,
  email: 'ravi@example.com',
  mobile: '9876543210',
  gender: 'M',
  dateOfBirth: '1998-05-15',
  address: '456 MG Road, Bengaluru',
  jobCity: 'Mumbai',
  currentCity: 'Bengaluru',
  currentDesignation: 'Software Engineer',
  totalExp: 3,
  currentCtc: 1200000,
  noticePeriodDays: 30,
  readyToRelocate: true,
  industry: 'IT Services',
  hasResume: true,
  resumeFileName: 'ravi-kumar-cv.pdf',
  resumeUploadedAt: '2026-08-10T10:00:00.000Z',
  resumeUrl: '/files/resume',
  cvPath: null,
  photoUrl: null,
  resumeHeadline: 'Full-stack developer',
  profileSummary: 'Experienced developer with React and Node.js',
  department: 'Engineering',
  roleCategory: 'Software Development',
  jobRole: 'Full Stack Developer',
  desiredJobType: 'Full Time',
  desiredEmploymentType: 'Permanent',
  preferredShift: 'Day',
  preferredWorkModes: 'Remote',
  preferredSalary: 1500000,
  preferredJobRoles: 'Full Stack Developer',
  maritalStatus: 'Single',
  preferredLocations: ['Mumbai', 'Bengaluru'],
  itSkills: [],
  certificates: [],
  projects: [],
  accomplishments: [],
  employment: [
    { employer: 'InfoTech', designation: 'Software Engineer', from: '2023-07', to: '', salary: 1200000, description: '', current: true },
  ],
  education: [
    { degree: 'B.Tech', course: 'Computer Science', institute: 'IIT Delhi', year: 2023, mode: 'Full Time', marks: '8.5 CGPA' },
  ],
  timeline: [
    { status: 'Application Received', at: '2026-08-15T10:00:00.000Z', comments: '' },
  ],
};

export const PENDING_REGISTRATION = {
  id: 1,
  companyName: 'NewCorp Pvt Ltd',
  emailCompany: 'info@newcorp.com',
  emailHR: 'hr@newcorp.com',
  location: 'Delhi',
  industryType: 'Manufacturing',
  status: 'Pending' as const,
  createdAt: '2026-08-28T10:00:00.000Z',
  reviewedAt: null,
};
