export const mockDashboard = {
  stats: [
    { id: 'totalJobs', label: 'Total Jobs', value: 48, delta: '+6%' },
    { id: 'activeJobs', label: 'Active Jobs', value: 22, delta: '+2' },
    { id: 'draftJobs', label: 'Draft Jobs', value: 7, delta: '-1' },
    { id: 'applicants', label: 'Applicants', value: 386, delta: '+18%' },
    { id: 'interviews', label: 'Interviews', value: 41, delta: '+5' },
    { id: 'hired', label: 'Hired', value: 14, delta: '+3' },
    { id: 'pendingPay', label: 'Pending Payments', value: '₹42k', delta: '2 due' },
  ],
  hiringTrend: [12, 18, 15, 22, 28, 24, 31, 35, 30, 38, 42, 40],
  monthlyApplicants: [40, 55, 48, 70, 82, 76, 90, 110, 95, 120, 130, 125],
  recentActivity: [
    { id: 1, text: 'Rahul Sharma applied to Senior Frontend Engineer', time: '12 min ago' },
    { id: 2, text: 'Interview scheduled with Priya Nair — Product Designer', time: '1 hr ago' },
    { id: 3, text: 'Draft job “Backend Engineer” saved', time: '3 hr ago' },
    { id: 4, text: 'Invoice INV-204 paid successfully', time: 'Yesterday' },
  ],
  upcomingInterviews: [
    { id: 1, name: 'Ananya Mehta', role: 'React Developer', when: 'Today, 3:00 PM', mode: 'Video' },
    { id: 2, name: 'Vikram Shah', role: 'QA Lead', when: 'Tomorrow, 11:30 AM', mode: 'Onsite' },
    { id: 3, name: 'Sofia Khan', role: 'UI Designer', when: 'Wed, 4:00 PM', mode: 'Video' },
  ],
  latestApplicants: [
    { id: 1, name: 'Rahul Sharma', role: 'Frontend Engineer', score: 92, exp: '5 yrs' },
    { id: 2, name: 'Neha Kapoor', role: 'HR Executive', score: 84, exp: '3 yrs' },
    { id: 3, name: 'Arjun Patel', role: 'DevOps Engineer', score: 88, exp: '6 yrs' },
  ],
};

export const mockJobs = [
  {
    id: 101,
    title: 'Senior Frontend Engineer',
    location: 'Bengaluru',
    experience: '4-7 yrs',
    salary: '18–28 LPA',
    applicants: 64,
    status: 'Active' as const,
    posted: '2026-07-28',
  },
  {
    id: 102,
    title: 'Product Designer',
    location: 'Remote',
    experience: '2-5 yrs',
    salary: '12–18 LPA',
    applicants: 41,
    status: 'Active' as const,
    posted: '2026-07-20',
  },
  {
    id: 103,
    title: 'Backend Engineer (Node)',
    location: 'Pune',
    experience: '3-6 yrs',
    salary: '15–22 LPA',
    applicants: 0,
    status: 'Draft' as const,
    posted: '2026-08-01',
  },
  {
    id: 104,
    title: 'QA Automation Lead',
    location: 'Hyderabad',
    experience: '5-8 yrs',
    salary: '16–24 LPA',
    applicants: 29,
    status: 'Closed' as const,
    posted: '2026-06-12',
  },
  {
    id: 105,
    title: 'Sales Manager',
    location: 'Mumbai',
    experience: '6-10 yrs',
    salary: '14–20 LPA',
    applicants: 18,
    status: 'Archived' as const,
    posted: '2026-05-02',
  },
];

export const mockApplicants = [
  {
    id: 1,
    name: 'Rahul Sharma',
    score: 92,
    experience: '5 yrs',
    skills: ['React', 'TypeScript', 'Node'],
    company: 'Infosys',
    notice: '30 days',
    status: 'New' as const,
    role: 'Senior Frontend Engineer',
  },
  {
    id: 2,
    name: 'Priya Nair',
    score: 87,
    experience: '4 yrs',
    skills: ['Figma', 'UX Research'],
    company: 'Flipkart',
    notice: '45 days',
    status: 'Shortlisted' as const,
    role: 'Product Designer',
  },
  {
    id: 3,
    name: 'Amit Desai',
    score: 78,
    experience: '6 yrs',
    skills: ['Python', 'Django', 'AWS'],
    company: 'TCS',
    notice: 'Immediate',
    status: 'Interview' as const,
    role: 'Backend Engineer',
  },
  {
    id: 4,
    name: 'Sneha Iyer',
    score: 95,
    experience: '7 yrs',
    skills: ['Lead', 'Hiring', 'ATS'],
    company: 'Accenture',
    notice: '60 days',
    status: 'Hired' as const,
    role: 'Engineering Manager',
  },
  {
    id: 5,
    name: 'Karan Malhotra',
    score: 61,
    experience: '2 yrs',
    skills: ['HTML', 'CSS'],
    company: 'Startup',
    notice: '15 days',
    status: 'Rejected' as const,
    role: 'Junior Frontend',
  },
];

export const mockInvoices = [
  { id: 'INV-204', candidate: 'Sneha Iyer', job: 'Engineering Manager', amount: 45000, gst: 8100, status: 'Paid' as const },
  { id: 'INV-211', candidate: 'Amit Desai', job: 'Backend Engineer', amount: 32000, gst: 5760, status: 'Pending' as const },
  { id: 'INV-218', candidate: 'Priya Nair', job: 'Product Designer', amount: 28000, gst: 5040, status: 'Outstanding' as const },
];
