export const employerPaths = {
  dashboard: '/company',
  completeProfile: '/company/profile',
  manageJobs: '/company/jobs',
  addJob: '/company/post-job',
  bulkImport: '/company/bulk-import',
  jobList: '/company/jobs',
  draftJobs: '/company/jobs/drafts',
  archivedJobs: '/company/jobs/archived',
  editJob: (id: string | number) => `/company/jobs/${id}/edit`,
  applicants: '/company/applicants',
  shortlisted: '/company/applicants/shortlisted',
  interviews: '/company/applicants/interviews',
  hired: '/company/applicants/hired',
  rejected: '/company/applicants/rejected',
  applicantProfile: (id: string | number) => `/company/applicants/${id}`,
  compare: '/company/compare-candidates',
  analytics: '/company/analytics',
  messages: '/company/messages',
  billing: '/company/billing',
  notifications: '/company/notifications',
  settings: '/company/settings',
} as const;
